#:schema node_modules/wrangler/config-schema.json
name = "sublink"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "8acaa34e629544c3a982bd46df1cde33" }
]

[assets]
directory = "./public"
